export type ConfidenceScore = number; // 0 to 100
export type TimeRequired = string; // e.g., "12 seconds"

/**
 * The standard base for any capability output.
 * Ensures that no engine is a black box.
 */
export interface ExplainableBase {
  confidence: ConfidenceScore;
  reason: string;
  assumptions: string[];
  sources: string[];
}

/**
 * A concrete recommendation output by the RecommendationEngine.
 */
export interface Recommendation extends ExplainableBase {
  type: 'RECOMMENDATION';
  actionTitle: string;
  expectedBenefit: string | number; // e.g., "KES 1,180/year"
  timeRequired: TimeRequired;
  impactScore: number; // 0-100, used by DecisionEngine for prioritization
  urgencyScore: number; // 0-100, used by DecisionEngine
  effortScore: number; // 0-100, used by DecisionEngine
}

/**
 * A narrative string generated by the NarrativeEngine.
 */
export interface Narrative extends ExplainableBase {
  type: 'NARRATIVE';
  text: string;
  tone: 'calm' | 'warning' | 'celebration' | 'neutral';
}

/**
 * A retrieved memory of past events from the MemoryEngine.
 */
export interface Memory extends ExplainableBase {
  type: 'MEMORY';
  eventDescription: string;
  timestamp: string;
  relevanceScore: number;
}

/**
 * Visual context indicators.
 */
export interface Insight extends ExplainableBase {
  type: 'INSIGHT';
  metric: string;
  status: 'positive' | 'negative' | 'neutral';
}

/**
 * The unified Capability Union.
 */
export type Capability = Recommendation | Narrative | Memory | Insight;

/**
 * The final output of the Decision Engine, selecting exactly ONE action.
 */
export interface Decision {
  winningRecommendation: Recommendation;
  rejectedAlternatives: Recommendation[];
}
